<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PermissionsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $permissions = [
            
            [
                'module' => null,
                'sidebar_menu' => 'academics',
                'old_id' => null,
                'section_id' => 1,
                'parent_id' => 0,
                'name' => 'categories',
                'route' => 'categories',
                'parent_route' => 'academics',
                'type' => 2,
                'lang_name' => 'common.categories',
                'icon' => null,
                'svg' => null,
                'status' => 1,
                'menu_status' => 1,
                'position' => 2,
                'is_saas' => 0,
                'relate_to_child' => 0,
                'is_menu' => 1,
                'is_admin' => 1,
                'is_teacher' => 0,
                'is_student' => 0,
                'is_parent' => 0,
                'is_alumni' => 0,
                'created_by' => 1,
                'updated_by' => 1,
                'permission_section' => 0,
                'alternate_module' => null,
                'user_id' => null,
                'role_id' => null,
                'school_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'custom_menu_id' => null,
            ],

            [
                'module' => null,
                'sidebar_menu' => 'academics',
                'old_id' => null,
                'section_id' => 1,
                'parent_id' => 0,
                'name' => 'pricing_plan_types',
                'route' => 'pricing_plan_types',
                'parent_route' => 'academics',
                'type' => 2,
                'lang_name' => 'academics.pricing_plan_types',
                'icon' => null,
                'svg' => null,
                'status' => 1,
                'menu_status' => 1,
                'position' => 2,
                'is_saas' => 0,
                'relate_to_child' => 0,
                'is_menu' => 1,
                'is_admin' => 1,
                'is_teacher' => 0,
                'is_student' => 0,
                'is_parent' => 0,
                'is_alumni' => 0,
                'created_by' => 1,
                'updated_by' => 1,
                'permission_section' => 0,
                'alternate_module' => null,
                'user_id' => null,
                'role_id' => null,
                'school_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'custom_menu_id' => null,
            ],
            [
                'module' => null,
                'sidebar_menu' => 'academics',
                'old_id' => null,
                'section_id' => 1,
                'parent_id' => 0,
                'name' => 'track_types',
                'route' => 'track_types',
                'parent_route' => 'academics',
                'type' => 2,
                'lang_name' => 'common.track_types',
                'icon' => null,
                'svg' => null,
                'status' => 1,
                'menu_status' => 1,
                'position' => 2,
                'is_saas' => 0,
                'relate_to_child' => 0,
                'is_menu' => 1,
                'is_admin' => 1,
                'is_teacher' => 0,
                'is_student' => 0,
                'is_parent' => 0,
                'is_alumni' => 0,
                'created_by' => 1,
                'updated_by' => 1,
                'permission_section' => 0,
                'alternate_module' => null,
                'user_id' => null,
                'role_id' => null,
                'school_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'custom_menu_id' => null,
            ],
            [
                'module' => null,
                'sidebar_menu' => 'academics',
                'old_id' => null,
                'section_id' => 1,
                'parent_id' => 0,
                'name' => 'discount_plans',
                'route' => 'discount_plans',
                'parent_route' => 'academics',
                'type' => 2,
                'lang_name' => 'academics.discount_plans',
                'icon' => null,
                'svg' => null,
                'status' => 1,
                'menu_status' => 1,
                'position' => 2,
                'is_saas' => 0,
                'relate_to_child' => 0,
                'is_menu' => 1,
                'is_admin' => 1,
                'is_teacher' => 0,
                'is_student' => 0,
                'is_parent' => 0,
                'is_alumni' => 0,
                'created_by' => 1,
                'updated_by' => 1,
                'permission_section' => 0,
                'alternate_module' => null,
                'user_id' => null,
                'role_id' => null,
                'school_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'custom_menu_id' => null,
            ],
            [
                'module' => null,
                'sidebar_menu' => 'academics',
                'old_id' => null,
                'section_id' => 1,
                'parent_id' => 0,
                'name' => 'Tracks',
                'route' => 'tracks',
                'parent_route' => 'academics',
                'type' => 2,
                'lang_name' => 'academics.tracks',
                'icon' => null,
                'svg' => null,
                'status' => 1,
                'menu_status' => 1,
                'position' => 2,
                'is_saas' => 0,
                'relate_to_child' => 0,
                'is_menu' => 1,
                'is_admin' => 1,
                'is_teacher' => 0,
                'is_student' => 0,
                'is_parent' => 0,
                'is_alumni' => 0,
                'created_by' => 1,
                'updated_by' => 1,
                'permission_section' => 0,
                'alternate_module' => null,
                'user_id' => null,
                'role_id' => null,
                'school_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'custom_menu_id' => null,
            ],
            // Add additional HR Section here...

            [
                'module' => null,
                'sidebar_menu' => 'human_resource',
                'old_id' => null,
                'section_id' => 1,
                'parent_id' => 0,
                'name' => 'emtype',
                'route' => 'emtype',
                'parent_route' => 'human_resource',
                'type' => 2,
                'lang_name' => 'hr.emtype',
                'icon' => null,
                'svg' => null,
                'status' => 1,
                'menu_status' => 1,
                'position' => 1,
                'is_saas' => 0,
                'relate_to_child' => 0,
                'is_menu' => 1,
                'is_admin' => 1,
                'is_teacher' => 0,
                'is_student' => 0,
                'is_parent' => 0,
                'is_alumni' => 0,
                'created_by' => 1,
                'updated_by' => 1,
                'permission_section' => 0,
                'alternate_module' => null,
                'user_id' => null,
                'role_id' => null,
                'school_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'custom_menu_id' => null,
            ],
            [
                'module' => null,
                'sidebar_menu' => 'human_resource',
                'old_id' => null,
                'section_id' => 1,
                'parent_id' => 0,
                'name' => 'slotemployee',
                'route' => 'slotemployee.index',
                'parent_route' => 'human_resource',
                'type' => 2,
                'lang_name' => 'hr.slotemployee',
                'icon' => null,
                'svg' => null,
                'status' => 1,
                'menu_status' => 1,
                'position' => 1,
                'is_saas' => 0,
                'relate_to_child' => 0,
                'is_menu' => 1,
                'is_admin' => 1,
                'is_teacher' => 0,
                'is_student' => 0,
                'is_parent' => 0,
                'is_alumni' => 0,
                'created_by' => 1,
                'updated_by' => 1,
                'permission_section' => 0,
                'alternate_module' => null,
                'user_id' => null,
                'role_id' => null,
                'school_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'custom_menu_id' => null,
            ],
            [
                'module' => null,
                'sidebar_menu' => 'human_resource',
                'old_id' => null,
                'section_id' => 1,
                'parent_id' => 0,
                'name' => 'specilization',
                'route' => 'specilization',
                'parent_route' => 'human_resource',
                'type' => 2,
                'lang_name' => 'hr.specilization',
                'icon' => null,
                'svg' => null,
                'status' => 1,
                'menu_status' => 1,
                'position' => 1,
                'is_saas' => 0,
                'relate_to_child' => 0,
                'is_menu' => 1,
                'is_admin' => 1,
                'is_teacher' => 0,
                'is_student' => 0,
                'is_parent' => 0,
                'is_alumni' => 0,
                'created_by' => 1,
                'updated_by' => 1,
                'permission_section' => 0,
                'alternate_module' => null,
                'user_id' => null,
                'role_id' => null,
                'school_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'custom_menu_id' => null,
            ],
            [
                'module' => null,
                'sidebar_menu' => 'human_resource',
                'old_id' => null,
                'section_id' => 1,
                'parent_id' => 0,
                'name' => 'calendar_staff',
                'route' => 'calendar_staff',
                'parent_route' => 'human_resource',
                'type' => 2,
                'lang_name' => 'hr.calendar_staff',
                'icon' => null,
                'svg' => null,
                'status' => 1,
                'menu_status' => 1,
                'position' => 1,
                'is_saas' => 0,
                'relate_to_child' => 0,
                'is_menu' => 1,
                'is_admin' => 1,
                'is_teacher' => 0,
                'is_student' => 0,
                'is_parent' => 0,
                'is_alumni' => 0,
                'created_by' => 1,
                'updated_by' => 1,
                'permission_section' => 0,
                'alternate_module' => null,
                'user_id' => null,
                'role_id' => null,
                'school_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'custom_menu_id' => null,
            ],
            [
                'module' => null,
                'sidebar_menu' => 'human_resource',
                'old_id' => null,
                'section_id' => 1,
                'parent_id' => 0,
                'name' => 'calendar_report',
                'route' => 'calendar_report',
                'parent_route' => 'human_resource',
                'type' => 2,
                'lang_name' => 'hr.calendar_report',
                'icon' => null,
                'svg' => null,
                'status' => 1,
                'menu_status' => 1,
                'position' => 1,
                'is_saas' => 0,
                'relate_to_child' => 0,
                'is_menu' => 1,
                'is_admin' => 1,
                'is_teacher' => 0,
                'is_student' => 0,
                'is_parent' => 0,
                'is_alumni' => 0,
                'created_by' => 1,
                'updated_by' => 1,
                'permission_section' => 0,
                'alternate_module' => null,
                'user_id' => null,
                'role_id' => null,
                'school_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'custom_menu_id' => null,
            ],
        ];

        // Remove existing records matching the route
        $routes = array_column($permissions, 'route');
        DB::table('permissions')->whereIn('route', $routes)->delete();

        // Insert new permissions
        DB::table('permissions')->insert($permissions);
    }
}
